### ISSUE TITLE
env sample file missed in the code base

### ISSUE THREAD

**Issue by yezhenqing** [StartHere-Ventures/django-easystart-open-source#3]
This is the first time I've come across a comprehensive project utilizing the Django-Inertia-Vue stacks—it's truly impressive!

But can you kindly provide the sample configuration file like ./compose/.env/dev-sample ??
I didn't find any env files from the folder of "compose".

Many thanks!

**Comment by Rub3nC** [comment]
Hi @yezhenqing Thank you for your kind words and interest in our project! We're glad to hear that you appreciate the Django-Inertia-Vue stack integration.  Could you please share your thoughts or suggestions on how we can improve?

We have uploaded the sample version of the environment file. It's already merged on the main branch.

We're delighted to hear from users like you. For more information about the project, you can access our detailed documentation here: [https://docs.djangoeasystart.com/](url)

Additionally, we offer a premium version of the software with more features, which is available at [https://djangoeasystart.com/](url) 

We are always looking to improve and value your suggestions. If you have any feature requests or ideas, we would be thrilled to hear them.

**Comment by yezhenqing** [comment]
Hi Ruben,
   Thanks for reaching out and appreciate your works by rapidly responding
to my request for the env file.
  I saw that webpack was used in the current code base, and certainly it is
good.
  Do you guys have any plans to add more options like include vite build
tools?  Just curious.

   This is a great project for the community of django-inertia-vue stacks,
I'm kind of passions for this integration.
I will keep my eyes on the progression of this project.

Best,
Zhenqing






Rubén Colina ***@***.***> 于2024年1月19日周五 16:12写道：
